"""
NexRecruit AI — Consolidated app.py
═════════════════════════════════════
Replaces the old app.py + app2.py confusion. Single file, four tabs:
  1. Recruiter Pipeline  — JD → LinkedIn → Score → Export
  2. Analytics           — Charts & insights on scored candidates
  3. Chatbot             — Ask anything about the JD / candidates
  4. Email Outreach      — Send personalised emails via Gmail

Key changes vs. old versions:
  • Gemini is now ACTUALLY wired in (JD extraction + scoring).
    Old code said "FULLY OFFLINE · NO API KEY" even though you had
    Gemini keys — the services/ layer was built but never imported.
  • Model updated from gemini-2.0-flash (shut down Jun 1 2026)
    to gemini-2.5-flash (current stable).
  • LinkedIn URL now includes quoted company name for real targeting.
    Also generates a Google X-ray search URL as a second, more precise
    option (site:linkedin.com/in "Company" "Role" skills).
  • Candidate upload accepts CSV *and* Excel (.xlsx).
    AI maps whatever column names the file uses — no manual reformatting.
  • Scoring: Gemini reads EVERY column in the candidate row (not just
    5 hardcoded fields), so activity signals, certifications, project
    history, etc. all influence the rank. Offline keyword scorer stays
    as a fallback when no key is present, with the location-match bug
    fixed (blank JD location no longer marks everyone "No match").
  • The Excel report is now GENERATED BY THE APP (scored data → openpyxl),
    not hand-crafted by you.
  • Analytics tab: score distribution, skill gap chart, location heatmap,
    experience histogram.
  • Chatbot tab: grounded on your JD + scored candidates, powered by
    your Gemini key.
"""

# ─── Bootstrap ─────────────────────────────────────────────────────────────────
from dotenv import load_dotenv
load_dotenv()

import streamlit as st
import pandas as pd
import json
import os
import pickle
import base64
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from core.parser import parse_jd_from_upload, parse_jd, parse_jd_with_ai, parse_jd_from_upload_with_ai
from core.scorer import load_candidates, score_candidates, detect_columns
from core.exporter import export_excel, export_csv
from core.linkedin import generate_linkedin_url, generate_xray_search_url
from core.cleaner import DataCleaner
from services.key_rotation import load_gemini_api_keys

# ─── Offline JD Parser (Qwen 2.5 7B via Ollama) ────────────────────────────────
from pathlib import Path
from parser import JDParser, OllamaError
from parser.cleaner import JDCleaner
from ui.jd_parser_animation import (
    render_parsing_animation,
    animate_reveal,
    qwen_to_legacy_shape,
    gemini_to_qwen_shape,
    extract_text_from_upload,
)
from ui.linkedin_tab import render_linkedin_tab

try:
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow
    from googleapiclient.discovery import build
    GMAIL_AVAILABLE = True
except ImportError:
    GMAIL_AVAILABLE = False

SCOPES     = ["https://www.googleapis.com/auth/gmail.send"]
TOKEN_FILE = "token.pickle"
CREDS_FILE = "credentials.json"

# ─── Page Config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="NexRecruit AI",
    page_icon="⬡",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Global CSS ─────────────────────────────────────────────────────────────────
st.markdown("""
<style>
  @import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=Outfit:wght@300;400;500;600&family=JetBrains+Mono:wght@400;500&display=swap');

  :root {
    --black:        #08080f;
    --black-mid:    #0f0f1a;
    --black-card:   #12121f;
    --purple:       #7c3aed;
    --purple-mid:   #9d5cf6;
    --purple-light: #c4b5fd;
    --purple-pale:  #1e1040;
    --border:       rgba(255,255,255,0.12);
    --border-p:     rgba(124,58,237,0.45);
    --green:        #10b981;
    --red:          #f43f5e;
    --amber:        #f59e0b;
  }

  html, body, [class*="css"] {
    font-family: 'Outfit', sans-serif !important;
    background: var(--black) !important;
    color: #ffffff !important;
    font-size: 16px !important;
  }

  ::-webkit-scrollbar { width: 5px; height: 5px; }
  ::-webkit-scrollbar-track { background: var(--black-mid); }
  ::-webkit-scrollbar-thumb { background: var(--purple); border-radius: 3px; }

  section[data-testid="stSidebar"] {
    background: var(--black-mid) !important;
    border-right: 1px solid var(--border) !important;
  }
  section[data-testid="stSidebar"] * { color: #ffffff !important; }

  .main .block-container { background: var(--black) !important; padding-top: 1.5rem; max-width: 1280px; }

  .page-header { padding: 1rem 0 0.5rem; }
  .page-header-pill {
    display: inline-flex; align-items: center; gap: 0.4rem;
    background: var(--purple-pale); border: 1px solid var(--border-p);
    border-radius: 999px; padding: 0.3rem 0.9rem;
    font-family: 'JetBrains Mono', monospace; font-size: 0.68rem;
    letter-spacing: 0.12em; text-transform: uppercase; color: var(--purple-light);
    margin-bottom: 0.6rem;
  }
  .page-header h1 {
    font-family: 'Syne', sans-serif; font-size: 2.4rem; font-weight: 800;
    letter-spacing: -0.03em; color: #fff; line-height: 1.15; margin: 0 0 0.3rem;
  }
  .page-header h1 .glow {
    background: linear-gradient(135deg, var(--purple-mid), var(--purple-light));
    -webkit-background-clip: text; -webkit-text-fill-color: transparent;
  }
  .page-header p {
    font-family: 'JetBrains Mono', monospace; font-size: 0.7rem;
    color: rgba(255,255,255,0.3); letter-spacing: 0.1em; text-transform: uppercase;
  }

  /* Step cards (white) */
  .step-card {
    background: #ffffff; border: 1px solid #e5e7eb; border-radius: 18px;
    padding: 1.75rem 2rem; margin-bottom: 1.5rem; position: relative; overflow: hidden;
  }
  .step-card::before {
    content: ''; position: absolute; top: 0; left: 0; right: 0; height: 3px;
    background: linear-gradient(90deg, var(--purple), var(--purple-light));
  }
  .step-card-glow {
    position: absolute; top: -60px; right: -60px; width: 200px; height: 200px;
    background: radial-gradient(circle, rgba(124,58,237,0.05) 0%, transparent 70%);
    pointer-events: none;
  }
  .step-num-badge {
    display: inline-flex; align-items: center; gap: 0.4rem;
    background: var(--purple-pale); border: 1px solid var(--border-p);
    border-radius: 8px; padding: 0.25rem 0.8rem;
    font-family: 'JetBrains Mono', monospace; font-size: 0.65rem;
    letter-spacing: 0.15em; text-transform: uppercase; color: var(--purple-light);
    margin-bottom: 0.5rem;
  }
  .step-title {
    font-family: 'Syne', sans-serif; font-size: 1.4rem; font-weight: 700;
    color: #111; margin-bottom: 1rem;
  }
  .step-card .stCaption { color: #9ca3af !important; }
  .step-card label { color: #374151 !important; }
  .step-card .stRadio label { color: #374151 !important; font-size: 0.9rem !important; }
  .step-card [data-testid="stAlert"] { background: #f5f3ff !important; border: 1px solid #e0d7ff !important; border-radius: 10px !important; color: #111 !important; }

  /* Dark analytics card */
  .dark-card {
    background: var(--black-card); border: 1px solid var(--border);
    border-radius: 16px; padding: 1.5rem 1.75rem; margin-bottom: 1.25rem;
  }

  /* Metric boxes */
  .metric-card {
    background: var(--black-card); border: 1px solid var(--border);
    border-radius: 14px; padding: 1.25rem 1.5rem; text-align: center;
  }
  .metric-card .m-value {
    font-family: 'Syne', sans-serif; font-size: 2rem; font-weight: 800;
    color: var(--purple-light); line-height: 1;
  }
  .metric-card .m-label {
    font-family: 'JetBrains Mono', monospace; font-size: 0.62rem;
    letter-spacing: 0.12em; text-transform: uppercase; color: rgba(255,255,255,0.35);
    margin-top: 0.4rem;
  }

  /* Candidate result cards */
  .cand-card {
    background: #ffffff; border: 1px solid #e5e7eb;
    border-radius: 14px; padding: 1.1rem 1.4rem; margin-bottom: 0.85rem;
    position: relative; overflow: hidden;
  }
  .cand-card::before {
    content: ''; position: absolute; top: 0; left: 0; bottom: 0; width: 4px;
  }
  .cand-card.score-high::before  { background: #10b981; }
  .cand-card.score-mid::before   { background: #f59e0b; }
  .cand-card.score-low::before   { background: #f43f5e; }
  .cand-rank {
    display: inline-flex; align-items: center; justify-content: center;
    width: 2rem; height: 2rem; border-radius: 8px;
    background: var(--purple-pale); border: 1.5px solid var(--border-p);
    font-family: 'Syne', sans-serif; font-weight: 800; font-size: 0.95rem;
    color: var(--purple-light); margin-right: 0.75rem; flex-shrink: 0;
  }
  .cand-name { font-family: 'Syne', sans-serif; font-weight: 700; font-size: 1.05rem; color: #111; }
  .cand-meta { font-family: 'JetBrains Mono', monospace; font-size: 0.68rem; color: #6b7280; letter-spacing: 0.05em; }
  .cand-score {
    font-family: 'Syne', sans-serif; font-weight: 800; font-size: 1.6rem;
    color: var(--purple); line-height: 1;
  }
  .cand-score-sub { font-family: 'JetBrains Mono', monospace; font-size: 0.6rem; color: #9ca3af; letter-spacing: 0.08em; }

  /* Skill tags */
  .tag {
    display: inline-flex; align-items: center; gap: 0.3rem;
    border-radius: 999px; padding: 0.2rem 0.7rem;
    font-family: 'JetBrains Mono', monospace; font-size: 0.65rem;
    font-weight: 500; margin: 0.15rem; letter-spacing: 0.04em;
  }
  .tag-match { background: #d1fae5; color: #065f46; }
  .tag-miss  { background: #fee2e2; color: #991b1b; }
  .tag-jd    { background: #ede9fe; color: #5b21b6; }

  /* Rationale box */
  .rationale-box {
    background: #f9fafb; border: 1px solid #f0f0f0; border-radius: 8px;
    padding: 0.5rem 0.85rem; margin-top: 0.5rem;
    font-size: 0.82rem; color: #4b5563; font-style: italic;
  }

  /* LinkedIn */
  .linkedin-card {
    background: var(--black-card); border: 1px solid var(--border-p);
    border-radius: 12px; padding: 1rem 1.25rem;
  }
  .li-label { font-family: 'JetBrains Mono', monospace; font-size: 0.62rem;
    letter-spacing: 0.12em; text-transform: uppercase; color: var(--purple-light); margin-bottom: 0.5rem; }
  .li-url { font-family: 'JetBrains Mono', monospace; font-size: 0.72rem; color: rgba(255,255,255,0.6); word-break: break-all; }

  /* JD fields */
  .jd-field { display: flex; align-items: baseline; gap: 0.6rem; margin-bottom: 0.45rem; }
  .jd-field .lbl { font-family: 'JetBrains Mono', monospace; font-size: 0.65rem; letter-spacing: 0.12em; text-transform: uppercase; color: #9ca3af; min-width: 90px; }
  .jd-field .val { font-size: 0.95rem; color: #111; font-weight: 500; }

  /* Chatbot */
  .chat-bubble-user {
    background: var(--purple); color: #fff; border-radius: 18px 18px 4px 18px;
    padding: 0.7rem 1rem; margin: 0.4rem 0 0.4rem 20%; font-size: 0.92rem; line-height: 1.6;
  }
  .chat-bubble-ai {
    background: #ffffff; color: #111; border-radius: 18px 18px 18px 4px;
    padding: 0.7rem 1rem; margin: 0.4rem 20% 0.4rem 0; font-size: 0.92rem; line-height: 1.6;
    border: 1px solid #e5e7eb;
  }
  .chat-sender { font-family: 'JetBrains Mono', monospace; font-size: 0.6rem; letter-spacing: 0.1em; text-transform: uppercase; color: rgba(255,255,255,0.35); margin-bottom: 0.2rem; }
  .chat-sender-ai { color: #9ca3af; }

  /* Source badge */
  .source-badge {
    display: inline-flex; align-items: center; gap: 0.35rem;
    background: rgba(16,185,129,0.12); border: 1px solid rgba(16,185,129,0.3);
    border-radius: 999px; padding: 0.2rem 0.7rem;
    font-family: 'JetBrains Mono', monospace; font-size: 0.6rem;
    letter-spacing: 0.1em; text-transform: uppercase; color: #10b981;
  }
  .source-badge.offline {
    background: rgba(245,158,11,0.12); border-color: rgba(245,158,11,0.3); color: #f59e0b;
  }

  /* Sidebar */
  .sidebar-brand { font-family: 'Syne', sans-serif; font-weight: 800; font-size: 1.3rem; color: #fff; margin-bottom: 0.1rem; }
  .sidebar-tagline { font-family: 'JetBrains Mono', monospace; font-size: 0.6rem; letter-spacing: 0.15em; text-transform: uppercase; color: rgba(255,255,255,0.3); margin-bottom: 1rem; }
  .sidebar-section-label { font-family: 'JetBrains Mono', monospace; font-size: 0.6rem; letter-spacing: 0.15em; text-transform: uppercase; color: rgba(255,255,255,0.3); margin-bottom: 0.5rem; }
  .sidebar-step { display: flex; align-items: flex-start; gap: 0.7rem; margin-bottom: 0.8rem; }
  .sidebar-step-num { font-family: 'JetBrains Mono', monospace; font-size: 0.7rem; background: var(--purple-pale); border: 1px solid var(--border-p); border-radius: 6px; padding: 0.15rem 0.5rem; color: var(--purple-light); flex-shrink: 0; }
  .sidebar-step-label { font-weight: 600; font-size: 0.85rem; color: #fff; }
  .sidebar-step-sub { font-family: 'JetBrains Mono', monospace; font-size: 0.62rem; color: rgba(255,255,255,0.3); letter-spacing: 0.06em; margin-top: 0.1rem; }

  /* Buttons */
  .stButton > button {
    background: linear-gradient(135deg, var(--purple) 0%, #9333ea 100%) !important;
    color: #fff !important; border: none !important; border-radius: 10px !important;
    font-family: 'Outfit', sans-serif !important; font-size: 0.92rem !important;
    font-weight: 600 !important; padding: 0.65rem 1.5rem !important;
    box-shadow: 0 0 18px rgba(124,58,237,0.25) !important;
    transition: box-shadow 0.2s !important;
  }
  .stButton > button:hover { box-shadow: 0 0 30px rgba(124,58,237,0.5) !important; }

  .step-card .stTextInput input, .step-card .stTextArea textarea {
    background: #f9fafb !important; border: 1px solid #e5e7eb !important;
    border-radius: 9px !important; color: #111 !important;
    font-family: 'Outfit', sans-serif !important;
  }
  [data-testid="stFileUploader"] {
    background: #f9fafb !important; border: 1.5px dashed rgba(124,58,237,0.35) !important;
    border-radius: 12px !important;
  }
  .step-card [data-testid="stFileUploader"] div { color: #374151 !important; }

  .stSelectbox select, .stMultiSelect select {
    background: #f9fafb !important; color: #111 !important;
  }
  .stDownloadButton > button {
    background: #ffffff !important; color: var(--purple) !important;
    border: 1.5px solid var(--border-p) !important; border-radius: 10px !important;
    font-weight: 600 !important;
  }
  hr { border-color: rgba(255,255,255,0.08) !important; }
  div[data-testid="stProgress"] > div > div { background: linear-gradient(90deg, var(--purple), var(--purple-light)) !important; }
  .stMultiSelect [data-baseweb="tag"] { background: var(--purple) !important; }
</style>
""", unsafe_allow_html=True)


# ─── Helpers ────────────────────────────────────────────────────────────────────

def _gemini_keys() -> list[str]:
    session_keys = st.session_state.get("_gemini_api_keys_input")
    return load_gemini_api_keys(session_keys)

def get_gmail_service():
    creds = None
    if os.path.exists(TOKEN_FILE):
        with open(TOKEN_FILE, "rb") as f:
            creds = pickle.load(f)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists(CREDS_FILE):
                return None, "credentials_missing"
            flow  = InstalledAppFlow.from_client_secrets_file(CREDS_FILE, SCOPES)
            creds = flow.run_local_server(port=0)
        with open(TOKEN_FILE, "wb") as f:
            pickle.dump(creds, f)
    try:
        return build("gmail", "v1", credentials=creds), "ok"
    except Exception as e:
        return None, str(e)

def send_email(service, to_email, subject, body):
    msg = MIMEMultipart("alternative")
    msg["To"]      = to_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))
    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    service.users().messages().send(userId="me", body={"raw": raw}).execute()

def generate_email_content(candidate_name, email_type, jd_role, company_name, sender_name):
    subjects = {
        "Interview Invitation":    f"Interview Invitation — {jd_role} at {company_name}",
        "Shortlisting Notice":     f"You've Been Shortlisted — {jd_role} at {company_name}",
        "Further Info Request":    f"Next Steps — {jd_role} Application at {company_name}",
        "Congratulations — Offer": f"🎉 Offer Letter — {jd_role} at {company_name}",
        "Rejection (Polite)":      f"Regarding Your Application — {jd_role} at {company_name}",
    }
    bodies = {
        "Interview Invitation": f"""Dear {candidate_name},

Thank you for your interest in the {jd_role} position at {company_name}.

After reviewing your profile, we are pleased to invite you for an interview. Your background makes you a strong candidate.

Interview Details:
• Position  : {jd_role}
• Format    : To be confirmed (Video / In-person)
• Duration  : Approximately 45–60 minutes

Please reply with your availability over the next 5 business days.

Warm regards,
{sender_name}
{company_name} — Talent Acquisition""",
        "Shortlisting Notice": f"""Dear {candidate_name},

We are pleased to inform you that you have been shortlisted for the {jd_role} role at {company_name}.

Your profile stood out and we would like to move forward. Our team will reach out with further details shortly.

Best regards,
{sender_name}
{company_name} — Talent Acquisition""",
        "Further Info Request": f"""Dear {candidate_name},

Thank you for applying for {jd_role} at {company_name}.

We'd like to learn more before proceeding. Could you share:
  1. A brief overview of your most relevant projects
  2. Your current notice period / availability
  3. Your expected compensation range (optional)

Regards,
{sender_name}
{company_name} — Talent Acquisition""",
        "Congratulations — Offer": f"""Dear {candidate_name},

Congratulations! 🎉

We are thrilled to extend an offer for the {jd_role} position at {company_name}. Please review the attached offer letter and confirm your acceptance by replying to this email.

Warmly,
{sender_name}
{company_name} — Talent Acquisition""",
        "Rejection (Polite)": f"""Dear {candidate_name},

Thank you sincerely for applying for the {jd_role} role at {company_name}.

After careful consideration, we have decided to move forward with other candidates whose experience more closely aligns with current requirements. We encourage you to apply for future openings.

We wish you the very best.

Kind regards,
{sender_name}
{company_name} — Talent Acquisition""",
    }
    return subjects.get(email_type, ""), bodies.get(email_type, "")

def _score_badge(score):
    if score >= 70: return "score-high"
    if score >= 45: return "score-mid"
    return "score-low"


# ─── Offline JD Parser helpers ──────────────────────────────────────────────────
@st.cache_resource
def _get_jd_parser() -> JDParser:
    """One JDParser per Streamlit session — avoids re-init on every rerun."""
    schema_path = Path(__file__).resolve().parent / "jd_schema.json"
    return JDParser(
        model="qwen2.5:7b-instruct",
        host="http://localhost:11434",
        schema_path=schema_path if schema_path.exists() else None,
        temperature=0.0,
        seed=42,
    )


def _parse_jd_chain(jd_text: str, container) -> dict | None:
    """
    Three-tier JD parsing chain with the typing animation wrapped around
    whichever layer succeeds first.

        Layer 1 · Gemini API   (online, fastest if keys are present)
        Layer 2 · Qwen 2.5 7B  (offline, via local Ollama)
        Layer 3 · Regex        (offline, deterministic — existing core.parser)

    The chain stops at the first layer that returns a usable result.
    All three populate both ``st.session_state.jd_data_full`` (rich Qwen
    shape — for the LinkedIn tab) and the returned legacy-shape dict
    (for the existing scorer / chatbot / email generator).

    Returns
    -------
    dict | None
        Legacy-shape JD on success, ``None`` if every layer failed.
    """

    # ── JD Cleaner (parser/cleaner.py) ─────────────────────────────────────
    # Strip boilerplate, invisible chars, bullet glyphs and collapse whitespace
    # before the text reaches any parsing layer.
    jd_text = JDCleaner().clean(jd_text)

    def _finalize(legacy: dict, rich: dict, engine_label: str) -> dict:
        """Common tail: stash full shape, run the typing animation, return legacy."""
        st.session_state.jd_data_full = rich
        animate_reveal(rich, container=container, engine_label=engine_label)
        return legacy

    # ── Layer 1: Gemini ────────────────────────────────────────────────────
    keys = _gemini_keys()
    if keys:
        try:
            gemini_jd = parse_jd_with_ai(jd_text, api_key=keys)
            gemini_dict = dict(gemini_jd or {})
            if gemini_dict.get("_source") == "gemini":
                gemini_dict["_source"] = "gemini"
                rich = gemini_to_qwen_shape(gemini_dict)
                return _finalize(gemini_dict, rich, "Gemini · cloud extraction")
            # Gemini call returned but its internal regex fallback fired —
            # fall through to Qwen rather than accept the regex result yet.
        except Exception as exc:  # noqa: BLE001 — log + fall through
            container.warning(f"Gemini failed ({exc}) — trying offline Qwen…")

    # ── Layer 2: Qwen 2.5 7B (offline) ─────────────────────────────────────
    try:
        # render_parsing_animation does parse + animation in one shot.
        qwen_dict = render_parsing_animation(_get_jd_parser(), jd_text, container=container)
        st.session_state.jd_data_full = qwen_dict
        legacy = qwen_to_legacy_shape(qwen_dict)
        legacy["_source"] = "qwen-offline"
        return legacy
    except OllamaError as exc:
        container.warning(f"Ollama unreachable ({exc}) — falling back to regex…")
    except Exception as exc:  # noqa: BLE001
        container.warning(f"Qwen parsing error ({exc}) — falling back to regex…")

    # ── Layer 3: Regex (offline, your existing core.parser) ────────────────
    try:
        regex_jd = parse_jd(jd_text)
        regex_dict = dict(regex_jd or {})
        regex_dict["_source"] = "offline-regex"
        rich = gemini_to_qwen_shape(regex_dict)
        return _finalize(regex_dict, rich, "Offline · regex extraction")
    except Exception as exc:  # noqa: BLE001
        container.error(f"All JD parsing layers failed: {exc}")
        return None


# ─── Session State Defaults ─────────────────────────────────────────────────────
defaults = {
    "jd_data": None, "jd_text": None, "jd_source": None,
    "jd_data_full": None,
    "candidates_df": None, "scored_df": None, "score_source": None,
    "col_map": {}, "name_col_detected": None,
    "linkedin_url": None, "xray_url": None,
    "selected_candidates": [], "email_drafts": {}, "send_log": [],
    "active_tab": "recruiter",
    "chat_history": [], "_jd_file_hash": None,
}
for k, v in defaults.items():
    if k not in st.session_state:
        st.session_state[k] = v


# ─── SIDEBAR ────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown('<div class="sidebar-brand">⬡ NexRecruit AI</div>', unsafe_allow_html=True)
    st.markdown('<div class="sidebar-tagline">AI-Powered Recruiting Suite</div>', unsafe_allow_html=True)
    st.divider()

    # ── Gemini API Keys ──
    st.markdown('<div class="sidebar-section-label">Gemini API Keys</div>', unsafe_allow_html=True)
    env_keys = load_gemini_api_keys()
    if env_keys:
        st.caption(f"{len(env_keys)} key(s) loaded from environment")
    key_input = st.text_area(
        "GEMINI_API_KEYS",
        value=st.session_state.get("_gemini_api_keys_input", ""),
        placeholder="Paste one key per line or separate them with commas",
        height=88,
        label_visibility="collapsed",
    )
    st.session_state["_gemini_api_keys_input"] = key_input
    st.divider()

    # ── Navigation ──
    st.markdown('<div class="sidebar-section-label">Navigation</div>', unsafe_allow_html=True)
    tabs_cfg = [
        ("recruiter",  "⬡",  "Recruiter"),
        ("linkedin",   "in", "LinkedIn"),
        ("analytics",  "📊", "Analytics"),
        ("chatbot",    "💬", "AI Chatbot"),
        ("email",      "✉",  "Email"),
    ]
    cols = st.columns(2)
    for i, (tab_id, icon, label) in enumerate(tabs_cfg):
        if cols[i % 2].button(f"{icon} {label}", key=f"nav_{tab_id}", width='stretch'):
            st.session_state.active_tab = tab_id
            st.rerun()

    # Active tab indicator bar
    bar_parts = []
    for tab_id, _, _ in tabs_cfg:
        active = st.session_state.active_tab == tab_id
        bg = "linear-gradient(90deg,var(--purple),var(--purple-light))" if active else "rgba(255,255,255,0.08)"
        bar_parts.append(f'<div style="flex:1;height:3px;border-radius:2px;background:{bg}"></div>')
    st.markdown(f'<div style="display:flex;gap:0.3rem;margin:0.3rem 0 0.75rem">{"".join(bar_parts)}</div>', unsafe_allow_html=True)

    st.divider()

    # ── Contextual sidebar ──
    active = st.session_state.active_tab
    if active == "recruiter":
        st.markdown('<div class="sidebar-section-label">Pipeline Steps</div>', unsafe_allow_html=True)
        for num, title, sub in [
            ("01", "Upload Job Description",  "PDF · DOCX · TXT"),
            ("02", "Extract Requirements",    "Gemini → Qwen → Regex"),
            ("03", "Upload Candidates",       "CSV or Excel — any columns"),
            ("04", "AI Score & Rank",         "Holistic scoring"),
            ("05", "Export Results",          "Auto-generated Excel report"),
        ]:
            st.markdown(f"""
            <div class="sidebar-step">
                <div class="sidebar-step-num">{num}</div>
                <div>
                  <div class="sidebar-step-label">{title}</div>
                  <div class="sidebar-step-sub">{sub}</div>
                </div>
            </div>""", unsafe_allow_html=True)
        st.divider()
        if st.session_state.jd_data:
            st.markdown(
                '<div style="background:rgba(10,102,194,0.08);border:1px solid rgba(10,102,194,0.22);'
                'border-radius:8px;padding:0.6rem 0.85rem;margin-bottom:0.6rem">'
                '<div style="font-family:\'JetBrains Mono\',monospace;font-size:0.6rem;'
                'letter-spacing:0.12em;text-transform:uppercase;color:#60a5fa">'
                '→ LinkedIn tab</div>'
                '<div style="font-size:0.78rem;color:rgba(255,255,255,0.55);margin-top:0.2rem">'
                'Generate Boolean / X-ray search queries</div></div>',
                unsafe_allow_html=True,
            )
        if st.session_state.scored_df is not None:
            n = len(st.session_state.scored_df)
            src = st.session_state.get("score_source", "")
            badge_cls = "source-badge" if src == "gemini" else "source-badge offline"
            src_label = "Gemini AI Scored" if src == "gemini" else "Offline Rule-Based"
            st.markdown(f"""
            <div style="background:rgba(16,185,129,0.1);border:1px solid rgba(16,185,129,0.25);
                        border-radius:8px;padding:0.7rem 0.9rem;margin-bottom:0.75rem">
              <div style="font-family:'JetBrains Mono',monospace;font-size:0.6rem;letter-spacing:0.12em;
                          text-transform:uppercase;color:#10b981">✓ Candidates Scored</div>
              <div style="font-family:'Syne',sans-serif;font-size:1.1rem;font-weight:700;color:#fff;margin-top:0.15rem">
                {n} ready
              </div>
              <div style="margin-top:0.4rem"><span class="{badge_cls}">{src_label}</span></div>
            </div>""", unsafe_allow_html=True)
            if st.button("✉  Email Outreach →", width='stretch'):
                st.session_state.active_tab = "email"
                st.rerun()

    elif active == "linkedin":
        st.markdown('<div class="sidebar-section-label">LinkedIn Search</div>', unsafe_allow_html=True)
        if st.session_state.jd_data_full is None:
            st.markdown(
                '<span style="font-size:0.78rem;color:rgba(255,255,255,0.40)">'
                'Parse a JD in the Recruiter tab to generate searches.</span>',
                unsafe_allow_html=True,
            )
        else:
            jd = st.session_state.jd_data_full
            st.markdown(
                f'<div style="font-size:0.82rem;color:rgba(255,255,255,0.65);line-height:1.7">'
                f'<strong style="color:#fff">{jd.get("job_title") or "—"}</strong><br>'
                f'<span style="color:#9ca3af">{jd.get("company_name") or "—"}</span><br>'
                f'<span style="color:#6b7280">{jd.get("location") or "—"}</span>'
                f'</div>', unsafe_allow_html=True,
            )
        st.divider()
        if st.button("⬡  Back to Recruiter ←", width='stretch', key="li_back"):
            st.session_state.active_tab = "recruiter"
            st.rerun()

    elif active == "analytics":
        st.markdown('<div class="sidebar-section-label">Analytics</div>', unsafe_allow_html=True)
        if st.session_state.scored_df is None:
            st.markdown('<span style="font-size:0.8rem;color:rgba(255,255,255,0.35)">Score candidates first to see analytics.</span>', unsafe_allow_html=True)
        else:
            n = len(st.session_state.scored_df)
            top = len(st.session_state.scored_df[st.session_state.scored_df["total_score"] >= 70])
            st.markdown(f'<span style="font-size:0.85rem;color:#c4b5fd">{top} / {n} candidates scored ≥70</span>', unsafe_allow_html=True)

    elif active == "chatbot":
        st.markdown('<div class="sidebar-section-label">Chat</div>', unsafe_allow_html=True)
        if not _gemini_keys():
            st.markdown('<span style="font-size:0.78rem;color:#f59e0b">⚠ Add Gemini key above to enable chat.</span>', unsafe_allow_html=True)
        else:
            st.markdown('<span style="font-size:0.8rem;color:#10b981">✓ Gemini key active</span>', unsafe_allow_html=True)
        if st.button("🗑  Clear Chat", width='stretch'):
            st.session_state.chat_history = []
            st.rerun()

    elif active == "email":
        st.markdown('<div class="sidebar-section-label">Sender Details</div>', unsafe_allow_html=True)
        _jd = st.session_state.jd_data or {}
        sender_name  = st.text_input("Your name",    value="Hiring Manager",          placeholder="Your Name",   key="sb_sender_name")
        company_name = st.text_input("Company",       value=_jd.get("company","") or "Your Company", placeholder="Company", key="sb_company")
        jd_role_e    = st.text_input("Role",          value=_jd.get("role","") or "Role",             placeholder="Role",    key="sb_role")
        st.divider()
        st.markdown('<div class="sidebar-section-label">Email Template</div>', unsafe_allow_html=True)
        email_type = st.selectbox("Template", [
            "Interview Invitation","Shortlisting Notice",
            "Further Info Request","Congratulations — Offer","Rejection (Polite)",
        ], label_visibility="collapsed", key="sb_email_type")
        st.divider()
        st.markdown('<div class="sidebar-section-label">Gmail</div>', unsafe_allow_html=True)
        if not GMAIL_AVAILABLE:
            st.markdown('<span style="color:#f43f5e;font-size:0.78rem">⚠ Gmail packages missing</span>', unsafe_allow_html=True)
        elif not os.path.exists(CREDS_FILE):
            st.markdown('<span style="color:#f59e0b;font-size:0.78rem">⚠ credentials.json missing</span>', unsafe_allow_html=True)
        elif os.path.exists(TOKEN_FILE):
            st.markdown('<span style="color:#10b981;font-size:0.82rem">✓ Gmail connected</span>', unsafe_allow_html=True)
        else:
            st.markdown('<span style="color:#f59e0b;font-size:0.78rem">○ Not authenticated</span>', unsafe_allow_html=True)
            if st.button("Connect Gmail", width='stretch'):
                svc, status = get_gmail_service()
                if status == "ok":
                    st.success("Gmail connected!")
                    st.rerun()
                else:
                    st.error(f"Auth failed: {status}")
        st.divider()
        if st.button("⬡  Back to Recruiter ←", width='stretch'):
            st.session_state.active_tab = "recruiter"
            st.rerun()


# ══════════════════════════════════════════════════════════════════════════════
# TAB: RECRUITER PIPELINE
# ══════════════════════════════════════════════════════════════════════════════
if st.session_state.active_tab == "recruiter":

    st.markdown("""
    <div class="page-header">
      <div class="page-header-pill">⬡ &nbsp; AI-Powered Recruiting</div>
      <h1>Find the <span class="glow">Right Talent</span><br>Faster Than Ever.</h1>
      <p>Upload JD → AI Extract → Score → Export → Email</p>
    </div>
    """, unsafe_allow_html=True)

    # ── STEP 1: Upload JD ──────────────────────────────────────────────────────
    st.markdown('<div class="step-card"><div class="step-card-glow"></div><div class="step-num-badge">⬡ &nbsp; Step 01</div><div class="step-title">Upload Job Description</div>', unsafe_allow_html=True)
    jd_col1, jd_col2 = st.columns([1, 1], gap="large")

    # Capture what (if anything) needs parsing this rerun.
    jd_text_to_parse: str | None = None
    file_hash_to_set: str | None = None

    with jd_col1:
        upload_mode = st.radio("Input method", ["Upload File (PDF / DOCX / TXT)", "Paste text"], horizontal=True)
        if upload_mode == "Upload File (PDF / DOCX / TXT)":
            jd_file = st.file_uploader("Drop your JD here", type=["pdf","docx","txt"], label_visibility="collapsed")
            if jd_file:
                import hashlib
                file_hash = hashlib.md5(jd_file.getvalue()).hexdigest()
                if st.session_state._jd_file_hash != file_hash:
                    extracted = extract_text_from_upload(jd_file)
                    if not extracted.strip():
                        st.error("Could not extract any text from this file.")
                    else:
                        jd_text_to_parse = extracted
                        file_hash_to_set = file_hash
        else:
            jd_text_pasted = st.text_area(
                "Paste JD text here", height=200,
                placeholder="Role: Data Scientist\nCompany: Acme Corp\nSkills: Python, ML, SQL\nLocation: Mumbai\nExperience: 3-5 years...",
                label_visibility="collapsed",
            )
            if st.button("⬡  Extract JD Details", width='stretch'):
                if jd_text_pasted.strip():
                    jd_text_to_parse = jd_text_pasted

        if st.session_state.jd_data:
            with st.expander("✏ Manually correct extracted fields", expanded=False):
                jd = st.session_state.jd_data
                ca, cb = st.columns(2)
                new_role    = ca.text_input("Role",    value=jd.get("role","") or "")
                new_company = cb.text_input("Company", value=jd.get("company","") or "")
                cc, cd = st.columns(2)
                new_loc     = cc.text_input("Location", value=jd.get("location","") or "")
                new_ind     = cd.text_input("Industry", value=jd.get("industry","") or "")
                if st.button("💾 Save Corrections"):
                    updated = dict(st.session_state.jd_data)
                    updated.update(role=new_role or updated.get("role"), company=new_company or updated.get("company"),
                                   location=new_loc or updated.get("location"), industry=new_ind or updated.get("industry"))
                    st.session_state.jd_data      = updated
                    st.session_state.linkedin_url = generate_linkedin_url(updated)
                    st.session_state.xray_url     = generate_xray_search_url(updated)
                    st.success("✓ Saved.")
                    st.rerun()

    # ── Right column: animate on fresh parse, static otherwise, empty if neither
    if jd_text_to_parse:
        # Three-tier chain: Gemini → Qwen → regex. Animation wraps the winner.
        legacy = _parse_jd_chain(jd_text_to_parse, jd_col2)

        if legacy:
            st.session_state.jd_data       = legacy
            st.session_state.jd_text       = jd_text_to_parse
            st.session_state.jd_source     = legacy.get("_source", "qwen-offline")
            st.session_state.linkedin_url  = generate_linkedin_url(legacy)
            st.session_state.xray_url      = generate_xray_search_url(legacy)
            if file_hash_to_set:
                st.session_state._jd_file_hash = file_hash_to_set

    elif st.session_state.jd_data:
        with jd_col2:
            jd = st.session_state.jd_data
            src = st.session_state.jd_source or "qwen-offline"
            badge_cls = "source-badge" if src in ("gemini", "qwen-offline") else "source-badge offline"
            src_label = {
                "gemini":           "✓ Gemini AI Extracted",
                "qwen-offline":     "✓ Qwen 2.5 · Offline",
                "offline-regex":    "⚠ Offline Regex Extracted",
            }.get(src, src)
            st.markdown(f'<div style="margin-bottom:0.75rem"><span class="{badge_cls}">{src_label}</span></div>', unsafe_allow_html=True)
            for label, value in [
                ("Role", jd.get("role","—")), ("Company", jd.get("company","—")),
                ("Location", jd.get("location","—")),
                ("Experience", f"{jd.get('experience_min','?')}–{jd.get('experience_max','?')} yrs"),
                ("Industry", jd.get("industry","—")), ("Type", jd.get("employment_type","—")),
                ("Education", jd.get("education","—")),
            ]:
                st.markdown(f'<div class="jd-field"><div class="lbl">{label}</div><div class="val">{value}</div></div>', unsafe_allow_html=True)
            skills = jd.get("skills", [])
            if skills:
                st.markdown("<br>", unsafe_allow_html=True)
                st.markdown("".join(f'<span class="tag tag-jd">{s}</span>' for s in skills), unsafe_allow_html=True)
            if jd.get("summary"):
                st.markdown(f'<div style="margin-top:0.75rem;background:#f5f3ff;border:1px solid #ede9fe;border-radius:10px;padding:0.75rem 1rem;font-size:0.88rem;color:#374151">📝 {jd["summary"]}</div>', unsafe_allow_html=True)
    else:
        with jd_col2:
            st.markdown("""
            <div style="border:1.5px dashed rgba(124,58,237,0.25);border-radius:14px;
                        padding:3rem 2rem;text-align:center;color:rgba(255,255,255,0.15)">
              <div style="font-size:2rem;margin-bottom:0.5rem">⬡</div>
              <div style="font-family:'JetBrains Mono',monospace;font-size:0.7rem;letter-spacing:0.12em;text-transform:uppercase">
                Parsed JD details will appear here
              </div>
            </div>""", unsafe_allow_html=True)
    st.markdown("</div>", unsafe_allow_html=True)

    # LinkedIn search now lives in its own tab — see the sidebar.

    # ── STEP 2: Upload Candidates ───────────────────────────────────────────────
    if st.session_state.jd_data:
        st.markdown('<div class="step-card"><div class="step-card-glow"></div><div class="step-num-badge">⬡ &nbsp; Step 02</div><div class="step-title">Upload Candidate Dataset</div>', unsafe_allow_html=True)

        tab_jsonl, tab_csv = st.tabs(["📄  JSONL (Hackathon Dataset)", "📊  CSV / Excel"])

        # ── Tab A: JSONL ──────────────────────────────────────────────────
        with tab_jsonl:
            ja, jb = st.columns([1, 1], gap="large")
            with ja:

                # ── Auto-detect candidates.jsonl on the machine ───────────
                import glob, os as _os

                def _find_jsonl() -> str:
                    """Search common locations for candidates.jsonl."""
                    search_roots = [
                        _os.getcwd(),                                    # where streamlit is running
                        _os.path.dirname(_os.path.abspath(__file__)),    # app.py's folder
                        _os.path.join(_os.path.expanduser("~"), "Downloads"),
                        _os.path.join(_os.path.expanduser("~"), "Desktop"),
                        _os.path.join(_os.path.expanduser("~"), "OneDrive"),
                        _os.path.join(_os.path.expanduser("~"), "Documents"),
                    ]
                    for root in search_roots:
                        for match in glob.glob(
                            _os.path.join(root, "**", "candidates.jsonl"),
                            recursive=True
                        ):
                            return match
                    return ""

                if "jsonl_auto_path" not in st.session_state:
                    st.session_state.jsonl_auto_path = _find_jsonl()

                # ── Option 1: Load directly from disk ────────────────────
                st.markdown("**⚡ Load from local path**")
                st.caption("Reads directly from disk — no browser upload limit.")

                detected = st.session_state.jsonl_auto_path
                if detected:
                    st.success(f"✓ Found: `{detected}`")
                else:
                    st.warning("Could not auto-detect — paste the full path below.")

                local_path = st.text_input(
                    "Path to candidates.jsonl",
                    value=detected,
                    placeholder=r"C:\Users\...\candidates.jsonl",
                    label_visibility="collapsed",
                    key="jsonl_local_path"
                )
                load_local = st.button("⚡ Load from Path", use_container_width=True, key="btn_load_local")

                st.markdown("<br>", unsafe_allow_html=True)

                # ── Option 2: Browser upload (fallback) ───────────────────
                st.markdown("**📁 Or upload file** *(only if under 200MB)*")
                jsonl_file = st.file_uploader(
                    "candidates.jsonl", type=["jsonl", "json"],
                    label_visibility="collapsed", key="jsonl_uploader"
                )

                # ── Shared loader function ────────────────────────────────
                def _load_jsonl_from_path(path: str):
                    import tempfile, os as _os
                    from parser.jsonl_reader import JSONLReader

                    if not Path(path).exists():
                        st.error(f"File not found: {path}")
                        return

                    with st.spinner(f"Reading {Path(path).name}… (100k candidates takes ~25s)"):
                        reader = JSONLReader(path, skip_invalid=True)
                        candidates_raw, parse_errors = reader.read_all()

                    cleaner = DataCleaner()
                    rows = []
                    for c in candidates_raw:
                        # Run core/cleaner.py DataCleaner on the raw candidate dict
                        # (standardises names, roles, locations, skills, experience,
                        #  validates fields and assigns quality_score / status).
                        # Use to_dict() so DataCleaner receives plain nested dicts,
                        # not nested dataclass objects (c.__dict__ kept ParsedProfile
                        # objects which made every .get("profile",{}).get(...) fail).
                        raw_dict = c.to_dict() if hasattr(c, "to_dict") else {}
                        try:
                            raw_dict = cleaner.clean_candidate(raw_dict)
                        except Exception:
                            pass  # if dict shape doesn't match, proceed uncleaned

                        p   = c.profile
                        sig = c.redrob_signals
                        edu_str = ""
                        if c.education:
                            edu_str = f"{c.education[0].degree} {c.education[0].institution}".strip()
                        rows.append({
                            "candidate_id":       c.candidate_id,
                            "name":               p.anonymized_name or c.candidate_id,
                            "role":               p.current_title,
                            "company":            p.current_company,
                            "location":           ", ".join(filter(None, [p.location, p.country])),
                            "experience":         p.years_of_experience,
                            "skills":             ", ".join(s.name for s in c.skills),
                            "education":          edu_str,
                            "email":              "",
                            "open_to_work":       sig.open_to_work_flag,
                            "notice_period_days": sig.notice_period_days,
                            "github_score":       sig.github_activity_score,
                            "response_rate":      sig.recruiter_response_rate,
                            "last_active":        sig.last_active_date or "",
                            "completeness":       sig.profile_completeness_score,
                            "quality_score":      raw_dict.get("quality_score", 100),
                            "data_status":        raw_dict.get("status", ""),
                            "warnings":           raw_dict.get("warnings", ""),
                        })

                    df = pd.DataFrame(rows)

                    # ── Blueprint split (datacleaning.md Step 5/6) ──────────
                    # Only Accepted / Needs Review candidates are scoring-eligible
                    # (validated_candidates.json). Rejected candidates are kept
                    # for audit only and must NOT enter the scoring pool
                    # (rejected_candidates.json -> Audit / Logs).
                    rejected_mask = df["data_status"] == "Rejected"
                    st.session_state.rejected_df = df[rejected_mask].reset_index(drop=True)
                    df = df[~rejected_mask].reset_index(drop=True)

                    st.session_state.candidates_df = df
                    st.session_state.col_map = {
                        "name": "name", "role": "role", "location": "location",
                        "experience": "experience", "skills": "skills",
                        "company": "company", "education": "education",
                    }
                    n_rejected = int(rejected_mask.sum())
                    st.success(
                        f"✓ {len(df):,} candidates loaded · {len(parse_errors)} skipped "
                        f"· {n_rejected:,} rejected by data-quality rules (excluded from scoring)"
                    )
                    if n_rejected:
                        with st.expander(f"⛔ {n_rejected:,} rejected candidates (excluded from scoring)"):
                            st.caption("These failed quality checks (quality_score < 50) and are kept for audit only — see Blueprint datacleaning.md Step 5/6.")
                            st.dataframe(
                                st.session_state.rejected_df[["candidate_id", "name", "quality_score", "warnings"]].head(20),
                                use_container_width=True
                            )
                    if parse_errors:
                        with st.expander(f"⚠ {len(parse_errors)} skipped"):
                            for e in parse_errors[:10]:
                                st.caption(f"Line {e.line_number}: {e.reason}")

                # ── Trigger: local path button ────────────────────────────
                if load_local and local_path.strip():
                    try:
                        _load_jsonl_from_path(local_path.strip())
                    except Exception as e:
                        st.error(f"Could not load: {e}")

                # ── Trigger: browser upload ───────────────────────────────
                if jsonl_file:
                    try:
                        import tempfile, os as _os
                        with tempfile.NamedTemporaryFile(
                            delete=False, suffix=".jsonl", mode="wb"
                        ) as tmp:
                            tmp.write(jsonl_file.read())
                            tmp_path = tmp.name
                        _load_jsonl_from_path(tmp_path)
                        _os.unlink(tmp_path)
                    except Exception as e:
                        st.error(f"Could not load JSONL: {e}")

            with jb:
                if st.session_state.candidates_df is not None:
                    st.caption("Preview — first 5 rows")
                    st.dataframe(
                        st.session_state.candidates_df.head(),
                        use_container_width=True, height=240
                    )

        # ── Tab B: CSV / Excel ────────────────────────────────────────────
        with tab_csv:
            ca, cb = st.columns([1, 1], gap="large")
            with ca:
                st.caption("CSV or Excel (.xlsx) — any column names. AI maps them automatically.")
                cand_file = st.file_uploader(
                    "Candidate file", type=["csv", "xlsx", "xls"],
                    label_visibility="collapsed", key="csv_uploader"
                )
                if cand_file:
                    try:
                        df = load_candidates(cand_file)
                        # NOTE: core/cleaner.py DataCleaner.clean_candidate() is built for
                        # the nested JSONL hackathon-dataset shape
                        # (profile / skills / education / redrob_signals — see
                        # Blueprint datacleaning.md). A generic CSV/Excel upload has
                        # flat, arbitrary column names (mapped later by detect_columns
                        # below), so DataCleaner cannot validate it — running it here
                        # silently did nothing useful (wrapped in try/except: pass)
                        # while implying rows had been quality-checked. Removed rather
                        # than left as dead/misleading code; CSV/Excel rows are NOT
                        # rejection-filtered, only AI-column-mapped.
                        st.session_state.candidates_df = df
                        st.success(f"✓ {len(df)} candidates loaded · {len(df.columns)} columns")
                        col_map = detect_columns(df, st.session_state.jd_data, api_key=_gemini_keys())
                        st.session_state.col_map = col_map
                        if col_map:
                            st.caption("Detected: " + " · ".join(f"{v}→{k}" for k, v in col_map.items()))
                    except Exception as e:
                        st.error(f"Could not load file: {e}")
            with cb:
                if st.session_state.candidates_df is not None:
                    st.caption("Preview — first 5 rows")
                    st.dataframe(
                        st.session_state.candidates_df.head(),
                        use_container_width=True, height=240
                    )

        st.markdown("</div>", unsafe_allow_html=True)

    # ── STEP 3: Score ───────────────────────────────────────────────────────────
    if st.session_state.jd_data and st.session_state.candidates_df is not None:
        st.markdown('<div class="step-card"><div class="step-card-glow"></div><div class="step-num-badge">⬡ &nbsp; Step 03</div><div class="step-title">AI Score & Rank Candidates</div>', unsafe_allow_html=True)
        sc1, sc2, sc3 = st.columns(3)
        keys = _gemini_keys()
        for col, lbl, pts, desc in [
            (sc1, "Skill Match", "40", "Required skills vs. candidate's full profile"),
            (sc2, "Role Match",  "30", "Title / seniority alignment"),
            (sc3, "Signal",      "30", "Location, career signals, activity, education"),
        ]:
            col.markdown(f"""
            <div class="metric-card" style="text-align:center">
              <div class="m-value">{pts}</div>
              <div class="m-label">{lbl} · max pts</div>
              <div style="font-size:0.72rem;color:rgba(255,255,255,0.3);margin-top:0.3rem">{desc}</div>
            </div>""", unsafe_allow_html=True)
        st.markdown("<br>", unsafe_allow_html=True)
        if keys:
            st.markdown('<span class="source-badge">⬡ Gemini AI Scoring</span>', unsafe_allow_html=True)
        else:
            st.markdown('<span class="source-badge offline">⚠ Offline Rule-Based Scoring (add Gemini key for AI)</span>', unsafe_allow_html=True)
        st.markdown("<br>", unsafe_allow_html=True)

        if st.button("⬡  Score All Candidates", width='stretch'):
            with st.spinner("Scoring candidates with Gemini AI… this takes ~10-20s for large datasets"):
                try:
                    scored, name_col, source = score_candidates(
                        st.session_state.candidates_df,
                        st.session_state.jd_data,
                        api_key=_gemini_keys()
                    )
                    st.session_state.scored_df         = scored
                    st.session_state.name_col_detected = name_col
                    st.session_state.score_source      = source
                    st.success(f"✓ Scored {len(scored)} candidates via {'Gemini AI' if source=='gemini' else 'offline rules'}")
                except Exception as e:
                    st.error(f"Scoring failed: {e}")

        if st.session_state.scored_df is not None:
            scored   = st.session_state.scored_df
            name_col = st.session_state.name_col_detected
            source   = st.session_state.score_source or "offline-rule"

            st.markdown("<br>", unsafe_allow_html=True)
            m1, m2, m3, m4 = st.columns(4)
            for col, val, lbl in [
                (m1, len(scored), "Total Candidates"),
                (m2, len(scored[scored["total_score"] >= 70]), "Strong Matches 70+"),
                (m3, round(float(scored["total_score"].mean()), 1), "Avg Score / 100"),
                (m4, int(scored["total_score"].max()), "Top Score"),
            ]:
                col.markdown(f'<div class="metric-card"><div class="m-value">{val}</div><div class="m-label">{lbl}</div></div>', unsafe_allow_html=True)
            st.markdown("<br>", unsafe_allow_html=True)

            top_n = st.slider("Show top N candidates", 5, min(50, len(scored)), min(10, len(scored)))
            for _, row in scored.head(top_n).iterrows():
                rank     = int(row.get("rank", 0))
                score    = int(row.get("total_score", 0))
                name_val = str(row[name_col]) if name_col and name_col in row.index else f"Candidate #{rank}"
                role_val = str(row.get(st.session_state.col_map.get("role","role"), row.get("role","—")))
                loc_val  = str(row.get(st.session_state.col_map.get("location","location"), row.get("location","—")))
                matched  = [s.strip() for s in str(row.get("matched_skills","")).split(",") if s.strip() and s.strip() != "None"]
                missing  = [s.strip() for s in str(row.get("missing_skills","")).split(",") if s.strip() and s.strip() != "None"]
                rationale = str(row.get("rationale",""))
                badge    = _score_badge(score)

                skill_sc  = int(row.get("skill_score", 0))
                role_sc   = int(row.get("role_score", 0))
                signal_sc = int(row.get("signal_score", 0))

                st.markdown(f"""
                <div class="cand-card {badge}">
                  <div style="display:flex;align-items:flex-start;justify-content:space-between">
                    <div style="display:flex;align-items:center">
                      <div class="cand-rank">#{rank}</div>
                      <div>
                        <div class="cand-name">{name_val}</div>
                        <div class="cand-meta">{role_val} &nbsp;·&nbsp; {loc_val}</div>
                        <div class="cand-meta" style="margin-top:0.15rem">
                          Skill {skill_sc}/40 &nbsp;·&nbsp; Role {role_sc}/30 &nbsp;·&nbsp; Signal {signal_sc}/30
                        </div>
                      </div>
                    </div>
                    <div style="text-align:right">
                      <div class="cand-score">{score}</div>
                      <div class="cand-score-sub">/ 100</div>
                    </div>
                  </div>
                  <div style="margin-top:0.6rem">
                    {"".join(f'<span class="tag tag-match">✓ {s}</span>' for s in matched)}
                    {"".join(f'<span class="tag tag-miss">✗ {s}</span>' for s in missing)}
                  </div>
                  {"" if not rationale or rationale == "nan" else f'<div class="rationale-box">💡 {rationale}</div>'}
                </div>""", unsafe_allow_html=True)

            st.markdown("<br>", unsafe_allow_html=True)
            if st.button("✉  Go to Email Outreach →", width='stretch'):
                st.session_state.active_tab = "email"
                st.rerun()

        st.markdown("</div>", unsafe_allow_html=True)

    # ── STEP 4: Export ─────────────────────────────────────────────────────────
    if st.session_state.scored_df is not None:
        st.markdown('<div class="step-card"><div class="step-card-glow"></div><div class="step-num-badge">⬡ &nbsp; Step 04</div><div class="step-title">Export Results</div>', unsafe_allow_html=True)
        col1, col2 = st.columns([1, 2], gap="large")
        with col1:
            excel_bytes = export_excel(
                st.session_state.scored_df,
                st.session_state.jd_data,
                col_map=st.session_state.col_map,
                score_source=st.session_state.score_source,
            )
            role_slug = (st.session_state.jd_data.get("role") or "candidates").replace(" ","_")
            st.download_button("⬇  Download Excel Report", excel_bytes,
                file_name=f"nexrecruit_{role_slug}.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", width='stretch')
            st.markdown("<br>", unsafe_allow_html=True)
            st.download_button("⬇  Download CSV", export_csv(st.session_state.scored_df),
                file_name="nexrecruit_results.csv", mime="text/csv", width='stretch')
        with col2:
            st.markdown("""
            <div style="background:#f5f3ff;border:1px solid #ede9fe;border-radius:12px;padding:1.25rem 1.5rem">
              <div style="font-family:'JetBrains Mono',monospace;font-size:0.62rem;letter-spacing:0.15em;
                          text-transform:uppercase;color:var(--purple);margin-bottom:0.75rem">⬡ Report Includes</div>
              <div style="font-size:0.88rem;color:#374151;line-height:2.1">
                ✅ Ranked candidates — colour-coded (green / amber / red)<br>
                ✅ AI rationale per candidate<br>
                ✅ Matched vs. missing skills breakdown<br>
                ✅ JD Summary sheet — all extracted fields<br>
                ✅ Score source label (AI or offline)
              </div>
            </div>""", unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)


# ══════════════════════════════════════════════════════════════════════════════
# TAB: LINKEDIN SEARCH QUERY
# ══════════════════════════════════════════════════════════════════════════════
elif st.session_state.active_tab == "linkedin":
    render_linkedin_tab(st.session_state.jd_data_full)


# ══════════════════════════════════════════════════════════════════════════════
# TAB: ANALYTICS
# ══════════════════════════════════════════════════════════════════════════════
elif st.session_state.active_tab == "analytics":
    st.markdown("""
    <div class="page-header">
      <div class="page-header-pill">📊 &nbsp; Analytics Dashboard</div>
      <h1>Candidate <span class="glow">Insights</span></h1>
      <p>Score distribution · Skill gaps · Location · Experience</p>
    </div>""", unsafe_allow_html=True)

    if st.session_state.scored_df is None:
        st.info("Score candidates in the Recruiter tab first to see analytics.")
    else:
        scored = st.session_state.scored_df
        jd     = st.session_state.jd_data or {}

        # ── Summary Metrics ──
        m1, m2, m3, m4, m5 = st.columns(5)
        top70 = len(scored[scored["total_score"] >= 70])
        top45 = len(scored[(scored["total_score"] >= 45) & (scored["total_score"] < 70)])
        low   = len(scored[scored["total_score"] < 45])
        for col, val, lbl in [
            (m1, len(scored), "Total"),
            (m2, top70, "Strong ≥70"),
            (m3, top45, "Good 45-69"),
            (m4, low, "Weak <45"),
            (m5, round(float(scored["total_score"].mean()), 1), "Avg Score"),
        ]:
            col.markdown(f'<div class="metric-card"><div class="m-value">{val}</div><div class="m-label">{lbl}</div></div>', unsafe_allow_html=True)
        st.markdown("<br>", unsafe_allow_html=True)

        ch1, ch2 = st.columns(2)
        with ch1:
            st.markdown('<div class="dark-card">', unsafe_allow_html=True)
            st.markdown("**Score Distribution**")
            bins = [0,20,40,60,70,80,100]
            labels = ["0-20","21-40","41-60","61-70","71-80","81-100"]
            cuts = pd.cut(scored["total_score"], bins=bins, labels=labels, right=True)
            dist = cuts.value_counts().reindex(labels).fillna(0)
            st.bar_chart(dist)
            st.markdown('</div>', unsafe_allow_html=True)

        with ch2:
            st.markdown('<div class="dark-card">', unsafe_allow_html=True)
            st.markdown("**Score Sub-Components (avg)**")
            avg_cols = {}
            for c in ["skill_score","role_score","signal_score","experience_score"]:
                if c in scored.columns:
                    avg_cols[c.replace("_score","").title()] = round(float(scored[c].mean()), 1)
            if avg_cols:
                st.bar_chart(pd.Series(avg_cols))
            else:
                st.info("No sub-score columns found.")
            st.markdown('</div>', unsafe_allow_html=True)

        # Skill gap chart
        if "missing_skills" in scored.columns:
            all_missing = []
            for cell in scored["missing_skills"].dropna():
                for s in str(cell).split(","):
                    s = s.strip()
                    if s and s.lower() not in ("none","nan",""):
                        all_missing.append(s.lower())
            if all_missing:
                miss_counts = pd.Series(all_missing).value_counts().head(12)
                st.markdown('<div class="dark-card">', unsafe_allow_html=True)
                st.markdown("**Top Missing Skills (Skill Gap)**")
                st.bar_chart(miss_counts)
                st.caption("These required skills are absent in the most candidates — prime areas for training or sourcing.")
                st.markdown('</div>', unsafe_allow_html=True)

        # Location breakdown
        col_map = st.session_state.col_map or {}
        loc_col = col_map.get("location") or ("location" if "location" in scored.columns else None)
        if loc_col and loc_col in scored.columns:
            ch3, ch4 = st.columns(2)
            with ch3:
                st.markdown('<div class="dark-card">', unsafe_allow_html=True)
                st.markdown("**Candidates by Location**")
                loc_counts = scored[loc_col].value_counts().head(10)
                st.bar_chart(loc_counts)
                st.markdown('</div>', unsafe_allow_html=True)

            exp_col = col_map.get("experience") or ("experience" if "experience" in scored.columns else None)
            if exp_col and exp_col in scored.columns:
                with ch4:
                    st.markdown('<div class="dark-card">', unsafe_allow_html=True)
                    st.markdown("**Experience Distribution (years)**")
                    import re
                    def _trynum(v):
                        m = re.search(r"\d+", str(v))
                        return float(m.group()) if m else None
                    exp_vals = scored[exp_col].apply(_trynum).dropna()
                    if not exp_vals.empty:
                        exp_bins = pd.cut(exp_vals, bins=[0,2,4,6,8,10,15,30], labels=["0-2","3-4","5-6","7-8","9-10","11-15","15+"])
                        st.bar_chart(exp_bins.value_counts().sort_index())
                    st.markdown('</div>', unsafe_allow_html=True)

        # Top candidates table
        st.markdown("#### 🏆 Top 10 Candidates")
        name_col = st.session_state.name_col_detected
        display_cols = ["rank","total_score","skill_score","role_score","signal_score","matched_skills"]
        if name_col and name_col in scored.columns:
            display_cols = [name_col] + display_cols
        st.dataframe(scored[display_cols].head(10), use_container_width=True)


# ══════════════════════════════════════════════════════════════════════════════
# TAB: CHATBOT
# ══════════════════════════════════════════════════════════════════════════════
elif st.session_state.active_tab == "chatbot":
    st.markdown("""
    <div class="page-header">
      <div class="page-header-pill">💬 &nbsp; AI Recruiting Assistant</div>
      <h1>Ask Anything About <span class="glow">Your Pipeline</span></h1>
      <p>Grounded on your JD + scored candidates · Powered by Gemini</p>
    </div>""", unsafe_allow_html=True)

    if not _gemini_keys():
        st.warning("⚠ Add your Gemini API key in the sidebar to enable the chatbot.")
    else:
        # Context for Gemini
        jd = st.session_state.jd_data or {}
        candidates_context = []
        if st.session_state.scored_df is not None:
            scored = st.session_state.scored_df
            name_col = st.session_state.name_col_detected
            for _, row in scored.head(20).iterrows():
                rec = {k: v for k, v in row.items() if not str(v) in ("nan","None") and pd.notna(v)}
                candidates_context.append(rec)

        context = {"jd": jd, "candidates": candidates_context}

        # Display chat history
        if not st.session_state.chat_history:
            st.markdown("""
            <div class="dark-card" style="text-align:center;padding:2rem">
              <div style="font-size:2rem;margin-bottom:0.5rem">💬</div>
              <div style="color:rgba(255,255,255,0.5);font-size:0.9rem">Ask me anything about the JD or candidates.</div>
              <div style="color:rgba(255,255,255,0.3);font-size:0.78rem;margin-top:0.75rem">
                Try: "Who is the best candidate and why?" · "Which candidates are missing Python?" · "Summarise the JD"
              </div>
            </div>""", unsafe_allow_html=True)
        else:
            st.markdown('<div class="dark-card" style="min-height:300px;max-height:500px;overflow-y:auto">', unsafe_allow_html=True)
            for msg in st.session_state.chat_history:
                role = msg["role"]
                content = msg["content"]
                if role == "user":
                    st.markdown(f'<div style="margin-bottom:0.3rem"><div class="chat-sender">You</div><div class="chat-bubble-user">{content}</div></div>', unsafe_allow_html=True)
                else:
                    st.markdown(f'<div style="margin-bottom:0.3rem"><div class="chat-sender chat-sender-ai">NexRecruit AI</div><div class="chat-bubble-ai">{content}</div></div>', unsafe_allow_html=True)
            st.markdown('</div>', unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)
        with st.form("chat_form", clear_on_submit=True):
            user_msg = st.text_input("Your question", placeholder="Who is the best candidate and why?", label_visibility="collapsed")
            send = st.form_submit_button("Send ➤", use_container_width=True)

        if send and user_msg.strip():
            st.session_state.chat_history.append({"role": "user", "content": user_msg})
            with st.spinner("Thinking…"):
                try:
                    from services.provider_factory import get_provider
                    provider = get_provider("gemini", _gemini_keys())
                    reply = provider.chat(
                        user_msg,
                        context=context,
                        history=st.session_state.chat_history[:-1],
                    )
                    st.session_state.chat_history.append({"role": "assistant", "content": reply})
                except Exception as e:
                    st.session_state.chat_history.append({"role": "assistant", "content": f"Error: {e}"})
            st.rerun()


# ══════════════════════════════════════════════════════════════════════════════
# TAB: EMAIL OUTREACH
# ══════════════════════════════════════════════════════════════════════════════
elif st.session_state.active_tab == "email":
    sender_name  = st.session_state.get("sb_sender_name", "Hiring Manager")
    company_name = st.session_state.get("sb_company", st.session_state.jd_data.get("company","Our Company") if st.session_state.jd_data else "Our Company")
    jd_role_e    = st.session_state.get("sb_role", st.session_state.jd_data.get("role","Role") if st.session_state.jd_data else "Role")
    email_type   = st.session_state.get("sb_email_type", "Interview Invitation")

    st.markdown("""
    <div class="page-header">
      <div class="page-header-pill">✉ &nbsp; Automated Email Outreach</div>
      <h1>Send <span class="glow">Personalised Emails</span><br>to Your Candidates.</h1>
      <p>Select → Review & Edit → Send via Gmail</p>
    </div>""", unsafe_allow_html=True)

    if not GMAIL_AVAILABLE or not os.path.exists(CREDS_FILE):
        st.markdown("""
        <div class="step-card"><div class="step-card-glow"></div>
        <div class="step-num-badge">✉ &nbsp; Setup Required</div>
        <div class="step-title">Gmail API Setup (Free · One-time)</div>
        <ol style="color:#374151;font-size:0.9rem;line-height:2.2">
          <li>Run: <code>pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib</code></li>
          <li>Go to <b>console.cloud.google.com</b> → New project → Enable Gmail API → Credentials → OAuth 2.0 Desktop → Download JSON → rename to <code>credentials.json</code> → place in app folder.</li>
          <li>Click <b>Connect Gmail</b> in the sidebar. Authenticates once, saves <code>token.pickle</code> permanently.</li>
        </ol>
        </div>""", unsafe_allow_html=True)

    # Load candidates
    st.markdown('<div class="step-card"><div class="step-card-glow"></div><div class="step-num-badge">✉ &nbsp; Step 01</div><div class="step-title">Candidate Data</div>', unsafe_allow_html=True)
    if st.session_state.scored_df is not None:
        n = len(st.session_state.scored_df)
        st.markdown(f'<div style="background:rgba(16,185,129,0.1);border:1px solid rgba(16,185,129,0.25);border-radius:10px;padding:0.8rem 1.1rem"><span style="color:#10b981;font-family:\'JetBrains Mono\',monospace;font-size:0.7rem">✓ {n} candidates from Recruiter tab</span></div>', unsafe_allow_html=True)
    up = st.file_uploader("Or upload scored CSV", type=["csv"], key="email_csv_up")
    if up:
        df_email = pd.read_csv(up)
        st.session_state.scored_df = df_email
        st.success(f"✓ Loaded {len(df_email)} candidates")
    st.markdown("</div>", unsafe_allow_html=True)

    if st.session_state.scored_df is not None:
        df   = st.session_state.scored_df
        name_col  = st.session_state.name_col_detected or df.columns[0]
        email_col = next((c for c in df.columns if "email" in c.lower()), None)
        score_col = "total_score" if "total_score" in df.columns else None

        # Select candidates
        st.markdown('<div class="step-card"><div class="step-card-glow"></div><div class="step-num-badge">✉ &nbsp; Step 02</div><div class="step-title">Select Candidates</div>', unsafe_allow_html=True)
        top_n_email = st.slider("Show top N", 5, min(50, len(df)), min(15, len(df)), key="email_topn")
        df_top = df.head(top_n_email)

        selections = []
        for _, row in df_top.iterrows():
            label = str(row[name_col]) if name_col in row.index else f"Row {_}"
            score_str = f" [{int(row[score_col])}/100]" if score_col else ""
            email_str = f" · {row[email_col]}" if email_col else ""
            if st.checkbox(f"{label}{score_str}{email_str}", key=f"sel_{_}"):
                selections.append(row)
        st.session_state.selected_candidates = selections
        st.markdown("</div>", unsafe_allow_html=True)

        # Preview & Send
        if st.session_state.selected_candidates:
            st.markdown('<div class="step-card"><div class="step-card-glow"></div><div class="step-num-badge">✉ &nbsp; Step 03</div><div class="step-title">Preview & Send</div>', unsafe_allow_html=True)
            for row in st.session_state.selected_candidates:
                cand_name = str(row[name_col]) if name_col in row.index else "Candidate"
                cand_email = str(row[email_col]) if email_col else ""
                subject, body = generate_email_content(cand_name, email_type, jd_role_e, company_name, sender_name)

                with st.expander(f"✉ {cand_name} — {email_type}", expanded=False):
                    new_body = st.text_area("Email body", value=body, height=240, key=f"body_{cand_name}")
                    st.session_state.email_drafts[cand_name] = (subject, new_body, cand_email)

            if st.button("📤  Send All Selected Emails", width='stretch'):
                svc = None
                if GMAIL_AVAILABLE and os.path.exists(CREDS_FILE):
                    svc, status = get_gmail_service()
                    if status != "ok":
                        st.error(f"Gmail auth failed: {status}")
                        svc = None
                sent_count = 0
                for cand_name, (subj, body, to_email) in st.session_state.email_drafts.items():
                    if svc and to_email and "@" in to_email:
                        try:
                            send_email(svc, to_email, subj, body)
                            st.session_state.send_log.append((cand_name, to_email, "✅ Sent"))
                            sent_count += 1
                        except Exception as e:
                            st.session_state.send_log.append((cand_name, to_email, f"❌ {e}"))
                    else:
                        st.session_state.send_log.append((cand_name, to_email or "—", "⚠ Simulated (no Gmail / no email)"))
                        sent_count += 1
                st.success(f"✓ Processed {sent_count} emails")
                st.rerun()

            if st.session_state.send_log:
                st.markdown("**Send Log:**")
                for name, email_addr, status in st.session_state.send_log:
                    st.markdown(f"`{name}` → `{email_addr}` — {status}")

            st.markdown("</div>", unsafe_allow_html=True)

# ── Footer ────────────────────────────────────────────────────────────────────
st.markdown("""
<div style="text-align:center;padding:2.5rem 0 1rem;font-family:'JetBrains Mono',monospace;
            font-size:0.6rem;letter-spacing:0.15em;text-transform:uppercase;color:rgba(255,255,255,0.12)">
  ⬡ NexRecruit AI · Intelligent · Precise
</div>""", unsafe_allow_html=True)